language: ruby
rvm:
  - 2.5.0
  - jruby
 - rbx-3

before_install:
  - gem install bundler -v 1.16.1
notifications:
    - false
scripts:
  - bundle exec rspec spec
after_script:
  - bundle exec rake coveralls:push
